[project]
name = "worrier-fitness"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "heyoo>=0.1.2",
    "python-dotenv>=1.1.0",
    "pywhatkit>=5.4",
]
